# Generated by Django 5.0.6 on 2024-12-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_loginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
    ]
