# Generated by Django 5.0.6 on 2024-11-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_menu_delete_modelapp2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(upload_to='menu_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kepuasan', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_set', to='home.postmenu')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
