# Generated by Django 5.0.6 on 2024-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_postmenu_rating_delete_category_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmenu',
            name='gambar',
            field=models.ImageField(upload_to='static/menu_images/'),
        ),
    ]
