# Generated by Django 5.0.6 on 2024-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_postmenu_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmenu',
            name='gambar',
            field=models.ImageField(upload_to='menu_images/'),
        ),
    ]
