# Generated by Django 5.0.6 on 2024-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_postmenu_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmenu',
            name='gambar',
            field=models.ImageField(upload_to='media/menu_images/'),
        ),
    ]
